{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vote-bot.name" . }}-svc
  labels:
    {{- include "vote-bot.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end}}
  selector:
    {{- include "vote-bot.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type}}
{{- end }}