apiVersion: v1
kind: Service
metadata:
  name: {{ include "web.name" . }}-svc
  labels:
    {{- include "web.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 2 }}
  {{- end}}
  selector:
    {{- include "web.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type}}