deployment:
  replicasCount: 1

  image:
    repository: "docker.l5d.io/buoyantio/emojivoto-web"
    tag: "v11"
    pullPolicy: "IfNotPresent"

  podAnnotations: {}

  ## Must be defined by array
  ports:
  - containerPort: 8080
    name: http

  defaultPort: 8080

  ## Must be defined by array
  env:
  - name: WEB_PORT
    value: "8080"
  - name: EMOJISVC_HOST
    value: emoji-svc.emojivoto:8080
  - name: VOTINGSVC_HOST
    value: voting-svc.emojivoto:8080
  - name: INDEX_BUNDLE
    value: dist/index_bundle.js

  securityContext:
    enabled: false
    spec: {}

  podSecurityContext:
    enabled: false
    spec: {}

serviceAccount:
  create: true
  name: "web"

service:
  type: ClusterIP

  ## Must be defined by array
  ports:
  - name: http
    port: 8080
    targetPort: 8080
