{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "voting.serviceAccountName" . }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent  4 }}
  {{- end }}
{{- end}}