deployment:
  replicasCount: 1

  image:
    repository: "docker.l5d.io/buoyantio/emojivoto-web"
    tag: "v11"
    pullPolicy: "IfNotPresent"

  podAnnotations: {}

  ## Must be defined by array
  ports: {}

  defaultPort: 8080

  ## Must be defined by array
  env:
  - name: WEB_HOST
    value: web-svc.emojivoto:8080

  securityContext:
    enabled: false
    spec: {}

  podSecurityContext:
    enabled: false
    spec: {}

serviceAccount:
  create: true 
  name: "vote-bot"

service:
  create: false
  type: {}
  ## Must be defined by array
  ports: {}
